sudo: false
language: generic
cache:
  directories:
  - $HOME/.stack
  - ./.stack-work
addons:
  apt:
    packages:
    - libgmp-dev
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards
  --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack --no-terminal --install-ghc test --only-dependencies
script:
- stack --no-terminal test --haddock --no-haddock-deps
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: ngZNAlU7RwoljShn0ZNFPfMGhMxIskAIFLgNwDHZR/LSwI4/O6AnUiPhMiLC6oqoJJ57dp7vDZcqtDmOJwzVlUL22WkqC849mzZsT35Qc8COQqSHMaEnN/M6Df+/BSRgsaHdF7K2xMZFJNaLuvhxLP6dFbfulNmjpIrWQJcmhjOdZ5Zpy2OG8N+S9NPj2TgWk/Y1jqftEeU7fkPqktfqnJpPdNPtiSztUDcmCPtpm1PtjyHX8aGWqeUpemXKUUnYuT/DxrCDISE5kpiixlq2wlHivGJ+JfBpB2g/OPGcZX+H83cnYh7CZuoux408dbefiag3NEJqWN/CEoAwigyVdBhcuMw/QkvVp9DvpVymsAZ0Hk5OPQeCVxtqOQ0+rvn+B1mNM/XayUnomAcJR+cdODaZsOxsIH5WD58eAQryTgEBkjSlvjNeXNzkLV4BGLlz433sQroAsMDFSx7KG18+JixZh6ry1wKMd21a0hkr6H5+OhBnvwDKYBLpLBC9tawsRiqak5+Ti7V0avwEu9DIYn40Nw822u6GMbNbZnU2ry7VwY+ew8JaCcJ2I2CuhnNm8y4+Z3s95VmstUIUbM3P+XKv6JzmcPogiPPMtLl1xv4o62MqjZhI1RknWVxpCWIpBGhiMR0rc0XYyQ+YigOdRb7+e6KHNCWiw73iI24tGGg=
  file: /home/travis/build/zhangyutong926/hsacnu-lock-control/.stack-work/install/x86_64-linux/lts-9.10/8.0.2/bin/HsacnuLockControl
  on:
    repo: zhangyutong926/hsacnu-lock-control
